questoes = ["(ENEM 2015) Apesar de seu disfarce de iniciativa e otimismo, o homem moderno está esmagado por um profundo sentimento de impotência que o faz olha fixamente e, como que paralisado, para as catástrofes que se avizinham. Por isso, desde já, saliente-se a necessidade de uma permanente atitude crítica, o único modo pelo qual o homem realizará sua vocação natural de integrar-se, superando a atitude do simples ajustamento ou acomodação, apreendendo temas e tarefas de sua época. FREIRE, P. Educação como prática da liberdade. Rio de Janeiro: Paz e Terra, 2011. Paulo Freire defende que a superação das dificuldades e apreensão o realidade atual será obtida pelo(a)",
"(ENEM 2015)Até o fim de 2007, quase 2 milhões de pessoas perderam suas casas e outros 4 milhões corriam o risco de ser despejadas. Os valores das casas despencaram em quase todos os EUA e muitas famílias acabaram devendo mais por suas casas do que o próprio valor do imóvel. Isso desencadeou uma espiral de execuções hipotecárias que diminuiu ainda mais os valores das casas. Em Cleveland, foi como se um “Katrina financeiro” atingisse a cidade. Casas abandonadas, com tábuas em janelas e portas, dominaram a paisagem nos bairros pobres, principalmente negros. Na Califórnia, também se enfileiraram casas abandonadas. HARVEY, D. O enigma do capital. São Paulo: Boitempo, 2011. Inicialmente restrita, a crise descrita no texto atingiu proporções globais, devido ao(à)",
"(ENEM 2015) A indústria têxtil utiliza grande quantidade de corantes no processo de tingimento dos tecidos. O escurecimento das águas dos rios causado pelo despejo desses corantes pode desencadear uma série de problemas no ecossistema aquático. Considerando esse escurecimento das águas, o impacto negativo inicial que ocorre é o(a)",
"(ENEM 2015) Algumas raças de cães domésticos não conseguem copular entre si devido à grande diferença em seus tamanhos corporais. Ainda assim, tal dificuldade reprodutiva não ocasiona a formação de novas espécies (especiação). Essa especiação não ocorre devido ao(à)",
"(ENEM 2015) Ao se apossarem do novo território, os europeus ignoraram um universo de antiga sabedoria, povoado por homens e bens unidos por um sistema integrado. A recusa em se inteirar dos valores culturais dos primeiros habitantes levou-os a uma descrição simplista desses grupos e à sua sucessiva destruição. Na verdade, não existe uma distinção entre a nossa arte e aquela produzida por povos tecnicamente menos desenvolvidos. As duas manifestações devem ser encaradas como expressões diferentes dos modos de sentir e pensar das várias sociedades, mas também como equivalentes, por resultarem de impulsos humanos comuns. SCATAMACHIA, M. C. M. In: AGUILAR, N. (Org.). Mostra do redescobrimento: arqueologia. São Paulo: Fundação Bienal de São Paulo – Associação Brasil 500 anos artes visuais, 2000. De acordo com o texto, inexiste distinção entre as artes produzidas pelos colonizadores e pelos colonizados, pois ambas compartilham o(a)",
"(ENEM 2015) Posso mandar por e-mail? Atualmente, é comum “disparar” currículos na internet com a expectativa de alcançar o maior número possível de selecionadores. Essa, no entanto, é uma ideia equivocada: é preciso saber quem vai receber seu currículo e se a vaga é realmente indicada para seu perfil, sob o risco de estar “queimando o filme” com um futuro empregador. Ao enviar o currículo por e-mail, tente saber quem vai recebê-lo e faça um texto sucinto de apresentação, com a sugestão a seguir: Assunto: Currículo para a vaga de gerente de marketing Mensagem: Boa tarde. Meu nome é José da Silva e gostaria de me candidatar à vaga de gerente de marketing. Meu currículo segue anexo. Guia da língua 2010: modelos e técnicas. Língua Portuguesa, 2010 (adaptado). O texto integra um guia de modelos e técnicas de elaboração de textos e cumpre a função social de ",
"(ENEM 2015) O tampo de vidro de uma mesa quebrou-se e deverá ser substituído por outro que tenha a forma de círculo. O suporte de apoio da mesa tem o formato de um prisma reto, de base em forma de triângulo equilátero com lados medindo 30 cm. Uma loja comercializa cinco tipos de tampos de vidro circulares com cortes já padronizados, cujos raios medem 18 cm, 26 cm, 30 cm, 35 cm e 60 cm. O proprietário da mesa deseja adquirir nessa loja o tampo de menor diâmetro que seja suficiente para cobrir a base superior do suporte da mesa. Considere 1,7 como aproximação para ¥ . O tampo a ser escolhido será aquele cujo raio, em centímetros, é igual a",
"(ENEM 2015) Uma fábrica de sorvetes utiliza embalagens plásticas no formato de paralelepípedo retangular reto. Internamente, a embalagem tem 10 cm de altura e base de 20 cm por 10 cm. No processo de confecção do sorvete, uma mistura é colocada na embalagem no estado líquido e, quando levada ao congelador, tem seu volume aumentado em 25%, ficando com consistência cremosa. Inicialmente é colocada na embalagem uma mistura sabor chocolate com volume de 1 000 cm3 e, após essa mistura ficar cremosa, será adicionada uma mistura sabor morango, de modo que, ao final do processo de congelamento, a embalagem fique completamente preenchida com sorvete, sem transbordar. O volume máximo, em cm³, da mistura sabor morango que deverá ser colocado na embalagem é",
"(ENEM 2016) Sentimos que toda satisfação de nossos desejos advinda do mundo assemelha-se à esmola que mantém hoje o mendigo vivo, porém prolonga amanhã a sua fome. A resignação, ao contrário, assemelha-se à fortuna herdada: livra o herdeiro para sempre de todas as preocupações. SCHOPENHAUER, A. Aforismo para a sabedoria da vida. São Paulo: Martins Fontes, 2005. O trecho destaca uma ideia remanescente de uma tradição filosófica ocidental, segundo a qual a felicidade se mostra indissociavelmente ligada à",
"(ENEM 2016) O que ocorreu na Bahia de 1798, ao contrário das outras situações de contestação política na América portuguesa, é que o projeto que lhe era subjacente não tocou somente na condição, ou no instrumento, da integração subordinada das colônias no império luso. Dessa feita, ao contrário do que se deu nas Minas Gerais (1789), a sedição avançou sobre a sua decorrência. JANCSÓ, I.; PIMENTA, J. P. Peças de um mosaico. In: MOTA, C. G. (Org.). Viagem incompleta: a experiência brasileira (1500-2000). São Paulo: Senac, 2000. A diferença entre as sedições abordadas no texto encontrava-se na pretensão de",
"(ENEM 2016) A usina de Itaipu é uma das maiores hidrelétricas do mundo em geração de energia. Com 20 unidades geradoras e 14 000 MW de potência total instalada, apresenta uma queda de 118,4 m e vazão nominal de 690 m3 /s por unidade geradora. O cálculo da potência teórica leva em conta a altura da massa de água represada pela barragem, a gravidade local (10 m/s2 ) e a densidade da água (1 000 kg/m3 ). A diferença entre a potência teórica e a instalada é a potência não aproveitada. Disponível em: www.itaipu.gov.br. Acesso em: 11 maio 2013 (adaptado). Qual é a potência, em MW, não aproveitada em cada unidade geradora de Itaipu?",
"(ENEM 2016) O carvão ativado é um material que possui elevado teor de carbono, sendo muito utilizado para a remoção de compostos orgânicos voláteis do meio, como o benzeno. Para a remoção desses compostos, utiliza-se a adsorção. Esse fenômeno ocorre por meio de interações do tipo intermoleculares entre a superfície do carvão (adsorvente) e o benzeno (adsorvato, substância adsorvida). No caso apresentado, entre o adsorvente e a substância adsorvida ocorre a formação de:",
"(ENEM 2016) Quem procura a essência de um conto no espaço que fica entre a obra e seu autor comete um erro: é muito melhor procurar não no terreno que fica entre o escritor e sua obra, mas justamente no terreno que fica entre o texto e seu leitor. OZ, A. De amor e trevas. São Paulo: Cia. das Letras, 2005 (fragmento). A progressão temática de um texto pode ser estruturada por meio de diferentes recursos coesivos, entre os quais se destaca a pontuação. Nesse texto, o emprego dos dois pontos caracteriza uma operação textual realizada com a finalidade de ",
"(ENEM 2016) Até que ponto replicar conteúdo é crime? “A internet e a pirataria são inseparáveis”, diz o diretor do instituto de pesquisas americano Social Science Research Council. “Há uma infraestrutura pequena para controlar quem é o dono dos arquivos que circulam na rede. Isso acabou com o controle sobre a propriedade e tem sido descrito como pirataria, mas é inerente à tecnologia”, afirma o diretor. O ato de distribuir cópias de um trabalho sem a autorização dos seus produtores pode, sim, ser considerado crime, mas nem sempre essa distribuição gratuita lesa os donos dos direitos autorais. Pelo contrário. Veja o caso do livro O alquimista, do escritor Paulo Coelho. Após publicar, para download gratuito, uma versão traduzida da obra em seu blog, Coelho viu as vendas do livro em papel explodirem. BARRETO, J.; MORAES, M. A internet existe sem pirataria? Veja, n. 2 308, 13 fev. 2013 (adaptado). De acordo com o texto, o impacto causado pela internet propicia a",
"(ENEM 2016) Em uma empresa de móveis, um cliente encomenda um guarda-roupa nas dimensões 220 cm de altura, 120 cm de largura e 50 cm de profundidade. Alguns dias depois, o projetista, com o desenho elaborado na escala 1 : 8, entra em contato com o cliente para fazer sua apresentação. No momento da impressão, o profissional percebe que o desenho não caberia na folha de papel que costumava usar. Para resolver o problema, configurou a impressora para que a figura fosse reduzida em 20%. A altura, a largura e a profundidade do desenho impresso para a apresentação serão, respectivamente,",
"(ENEM 2016) Uma liga metálica sai do forno a uma temperatura de de 3000 °C e diminui 1 por cento de sua temperatura a cada 30 min. Use 0,477 como aproximação para log10(3) e 1,041 como aproximação para log10(11). O tempo decorrido, em hora, até que a liga atinja 30 °C é mais próximo de",
"(ENEM 2017) Mas assim que penetramos no universo da web, descobrimos que ele constitui não apenas um imenso “território” em expansão acelerada, mas que também oferece inúmeros “mapas”, filtros, seleções para ajudar o navegante a orientar-se. O melhor guia para a web é a própria web. Ainda que seja preciso ter a paciência de explorá-la. Ainda que seja preciso arriscar-se a ficar perdido, aceitar “a perda de tempo” para familiarizar-se com esta terra estranha. Talvez seja preciso ceder por um instante a seu aspecto lúdico para descobrir, no desvio de um link, os sites que mais se aproximam de nossos interesses profissionais ou de nossas paixões e que poderão, portanto, alimentar da melhor maneira possível nossa jornada pessoal. LÉVY, P. Cibercultura. São Paulo: Editora 34, 1999. O usuário iniciante sente-se não raramente desorientado no oceano de informações e possibilidades disponíveis na rede mundial de computadores. Nesse sentido, Pierre Lévy destaca como um dos principais aspectos da internet o(a)", 
"(ENEM 2017) Essas moças tinham o vezo de afirmar o contrário do que desejavam. Notei a singularidade quando principiaram a elogiar o meu paletó cor de macaco. Examinavam-no sérias, achavam o pano e os aviamentos de qualidade superior, o feitio admirável. Envaideci-me: nunca havia reparado em tais vantagens. Mas os gabos se prolongaram, trouxeram-me desconfiança. Percebi afinal que elas zombavam e não me susceptibilizei. Longe disso: achei curiosa aquela maneira de falar pelo avesso, diferente das grosserias a que me habituara. Em geral me diziam com franqueza que a roupa não me assentava no corpo, sobrava nos sovacos. RAMOS, G. Infância. Rio de Janeiro: Record,1994. Por meio de recursos linguísticos, os textos mobilizam estratégias para introduzir e retomar ideias, promovendo a progressão do tema. No fragmento transcrito, um novo aspecto do tema é introduzido pela expressão",
"(ENEM 2017) A moralidade, Bentham exortava, não é uma questão de agradar a Deus, muito menos de fidelidade a regras abstratas. A moralidade é a tentativa de criar a maior quantidade de felicidade possível neste mundo. Ao decidir o que fazer, deveríamos, portanto, perguntar qual curso de conduta promoveria a maior quantidade de felicidade para todos aqueles que serão afetados. RACHELS, J. Os elementos da filosofia moral. Barueri-SP: Manole,2006. Os parâmetros da ação indicados no texto estão em conformidade com uma",
"(ENEM 2017) México, Colômbia, Peru e Chile decidiram seguir um caminho mais curto para a integração regional. Os quatro países, em meados de 2012, criaram a Aliança do Pacífico e eliminaram, em 2013, as tarifas aduaneiras de 90por cento do total de produtos comercializados entre suas fronteiras. OLIVEIRA,E. Aliança do Pacífico se fortalece e Mercosul fica à sua sombra. O Globo, 24 fev. 2013 (adaptado). O acordo descrito no texto teve como objetivo econômico para os países-membros",
"(ENEM 2017) Os medicamentos são rotineiramente utilizados pelo ser humano com o intuito de diminuir ou, por muitas vezes, curar possíveis transtornos de saúde. Os antibióticos são grupos de fármacos inseridos no tratamento de doenças causadas por bactérias. Na terapêutica das doenças mencionadas, alguns desses fármacos atuam ",
"(ENEM 2017) Na Idade Média, para elaborar preparados a partir de plantas produtoras de óleos essenciais, as coletas das espécies eram realizadas ao raiar do dia. Naquela época, essa prática era fundamentada misticamente pelo efeito mágico dos raios lunares, que seria anulado pela emissão dos raios solares. Com a evolução da ciência, foi comprovado que a coleta de algumas espécies ao raiar do dia garante a obtenção de material com maiores quantidades de óleos essenciais. A explicação científica que justifica essa prática se baseia na",
"(ENEM 2017) Em um teleférico turístico, bondinhos saem de estações ao nível do mar e do topo de uma montanha. A travessia dura 1,5 minuto e ambos os bondinhos se deslocam à mesma velocidade. Quarenta segundos após o bondinho A partir da estação ao nível do mar, ele cruza com o bondinho B, que havia saído do topo da montanha. Quantos segundos após a partida do bondinho B partiu o bondinho A?",
"(ENEM 2017) Em uma de suas viagens, um turista comprou uma lembrança de um dos monumentos que visitou. Na base do objeto há informações dizendo que se trata de uma peça em escala 1 : 400, e que seu volume é de 25 cm3 . O volume do monumento original, em metro cúbico, é de",
"(ENEM 2018) Na sociologia e na literatura, o brasileiro foi por vezes tratado como cordial e hospitaleiro, mas não é isso o que acontece nas redes sociais: a democracia racial apregoada por Gilberto Freyre passa ao largo do que acontece diariamente nas comunidades virtuais do país. Levantamento inédito realizado pelo projeto Comunica que Muda [...] mostra em números a intolerância do internauta tupiniquim. Entre abril e junho, um algoritmo vasculhou plataformas [...] atrás de mensagens e textos sobre temas sensíveis, como racismo, posicionamento político e homofobia. Foram identificados 393 284 menções, sendo 84 por cento delas com abordagem negativa, de exposição do preconceito e da discriminação. Disponível em http://oglobo.globo.com. Acesso em: 6 dez, 2017 (adaptado). Ao abordar a postura do internauta brasileiro mapeada por meio de uma pesquisa em plataformas virtuais, o texto",
"(ENEM 2018) Vó Clarissa deixou cair os talheres no prato, fazendo a porcelana estalar. Joaquim, meu primo, continuava com o queixo suspenso, batendo com o garfo nos lábios, esperando a resposta. Beatriz ecoou a palavra como pergunta, “o que é lésbica?”. Eu fiquei muda. Joaquim sabia sobre mim e me entregaria para a vó e, mais tarde, para toda a família. Senti um calor letal subir pelo meu pescoço e me doer atrás das orelhas. Previ a cena: vó, a senhora é lésbica? Porque a Joana é. A vergonha estava na minha cara e me denunciava antes mesmo da delação. Apertei os olhos e contraí o peito, esperando o tiro. [...] [...] Pensei na naturalidade com que Taís e eu levávamos a nossa história. Pensei na minha insegurança de contar isso à minha família, pensei em todos os colegas e professores que já sabiam, fechei os olhos e vi a boca da minha vó e a boca da tia Carolina se tocando, apesar de todos os impedimentos. Eu quis saber mais, eu quis saber tudo, mas não consegui perguntar. POLESSO, N. B. Vó, a senhora é lésbica? Amora. Porto Alegre: Não Editora, 2015 (fragmento). A situação narrada revela uma tensão fundamentada na perspectiva do",
"(ENEM 2018) No Segundo Congresso Internacional de Ciências Geog´raficas, em 175, a que compareceram o presidente da República, o governador de Paris e o presidente da República, o governador de Paris e o presidente da Assembleia, o discurso inaugural do almirante La Roucière-Le Noury expôs a atitude predominante no encontro: “Cavalheiros, a Providência nos ditou a obrigação de conhecer e conquistar a terra. Essa ordem suprema é um dos deveres imperiosos inscritos em nossas inteligências e nossas atividades. A geografia, essa ciência que inspira tão bela devoção e em cujo nome foram sacrificadas tantas vítimas, tornou-se a filosofia da terra. SAID, E. Cultura e política. São Paulo: Cia. das Letras, 1995. No contexto histórico apresentado, a exaltação da ciência geográfica decorre do seu uso para o(a)",
"(ENEM 2018) )Foi-se o tempo em que era possível mostrar um mundo econômico organizado em camadas bem definidas, onde grandes centros urbanos se ligavam, por si próprios, a economias adjacentes “lentas”, com o ritmo muito mais rápido do comércio e das finanças de longo alcance. Hoje tudo ocorre como se essas camadas sobrepostas estivessem mescladas e interpermeadas. Interdependências de curto e longo alcance não podem mais ser separadas umas das outras. BRENNER, N. A globalização como reterritorialização. Cadernos Metrópole, n. 24, jul. - dez. 2010 (adaptado) A maior complexidade dos espaços urbanos contemporâneos ressaltada no texto explica-se pela",
"(ENEM 2018) O século XVIII é, por diversas razões, um século diferenciado. Razão e experimentação se aliavam no que se acreditava ser o verdadeiro caminho para o estabelecimento do conhecimento científico, por tanto tempo almejado. O fato, a análise e a indução passavam a ser parceiros fundamentais da razão. É ainda no século XVIII que o homem começa a tomar consciência de sua situação na história. ODALIA, N. In: PINSKY, J.; PINSKY, C. B. História da cidadania. São Paulo. Contexto, 2003. No ambiente cultural do Antigo Regime, a discussão filosófica mencionada no texto tinha como uma de suas características a",
"(ENEM 2018) Para serem absorvidos pelas células do intestino humano, os lipídios ingeridos precisam ser primeiramente emulsificados. Nessa etapa da digestão, torna-se necessária a ação dos ácidos biliares, visto que os lipídios apresentam uma natureza apolar e são insolúveis em água. Esses ácidos atuam no processo de modo a",
"(ENEM 2018) A prefeitura de um pequeno município do interior decide colocar apenas postes para a iluminação ao longo de uma estrada retilínea, que inicia em uma praça centrale termina numa fazenda na zona rural. Como a praça já possui iluminação, o primeiro poste será colocado a 80 metros da praça, o segundo, a 100 metros, o terceiro, a 120 metros, e assim sucessivamente, mantendo-se sempre uma distância de vinte metros entre os postes,até que o último poste seja colocado a uma distância de 1 380 metros da praça.Se a prefeitura pode pagar, no máximo, R$ 8000,00 por poste colocado, o maior valor que poderá gastar com a colocação desses postes é" ,
"(ENEM 2018) Um produtor de milho utiliza uma área de 160 hectares para as suas atividades agrícolas. Essa área é dividida em duas partes: uma de 40 hectares, com menor produtividade. A produtividade é dada pela razão entre a produção, em toneladas, e a área cultivada. Sabe-se que a área de 40 hectares tem produtividade igual a 2,5 vezes à da outra. Esse fazendeiro pretende aumentar sua produção total em 15%, aumentando o tamanho sua propriedade. Para tanto, pretende comprar uma parte de uma fazenda vizinha, que possui a mesma produtividade da parte de 120 hectares de suas terras. Qual é a área mínima, em hectare, que o produtor precisará comprar? ",
"(ENEM 2019) Meu caro Sherlock Holmes, algo horrível aconteceu às três da manhã no Jardim Lauriston. Nosso homem que estava na vigia viu uma luz às duas da manhã saindo de uma casa vazia. Quando se aproximou, encontrou a porta aberta e, na sala da frente, o corpo de um cavalheiro bem vestido. Os cartões que estavam em seu bolso tinham o nome de Enoch J. Drebber, Cleveland, Ohio, EUA. Não houve assalto e nosso homem não conseguiu encontrar algo que indicasse como ele morreu. Não havia marcas de sangue, nem feridas nele. Não sabemos como ele entrou na casa vazia. Na verdade, todo assunto é um quebra-cabeça sem fim. Se puder vir até a casa seria ótimo, se não, eu lhe conto os detalhes e gostaria muito de saber sua opinião. Atenciosamente, Tobias Gregson. DOYLE, A. C. Um estudo em vermelho. Cotia: Pé de Letra, 2017. Considerando o objetivo da carta de Tobias Gregson, a sequência de enunciados negativos presente nesse texto tem a função de", 
"(ENEM 2019) Com o enredo que homenageou o centenário do Rei do Baião, Luiz Gonzaga, a Unidos da Tijuca foi coroada no Carnaval 2012. A penúltima escola a entrar na Sapucaí, na segunda noite de desfiles, mergulhou no universo do cantor e compositor brasileiro e trouxe a cultura nordestina com criatividade para a Avenida, com o enredo O dia em que toda a realeza desembarcou na Avenida para coroar o Rei Luiz do Sertão. Disponível em: www.cultura.rj.gov.br. Acesso em: 15 maio 2012 (adaptado). A notícia relata um evento cultural que marca a",
"(ENEM 2019) A pegada ecológica gigante que estamos a deixar no planeta está a transformá-lo de tal forma que os especialistas consideram que já entramos numa nova época geológica, o Antropoceno. E muitos defendem que, se não travarmos a crise ambiental, mais rapidamente transformaremos a Terra em Vênus do que iremos a Marte. A expressão “Antropoceno” é atribuída ao químico e prêmio Nobel Paul Crutzen, que a propôs durante uma conferência em 2000, ao mesmo tempo que anunciou o fim do Holoceno — a época geológica em que os seres humanos se encontram há cerca de 12 mil anos, segundo a União Internacional das Ciências Geológicas (UICG), a entidade que define as unidades de tempo geológicas. SILVA, R. D. Antropoceno: e se formos os últimos seres vivos a alterar a Terra? Disponível em: www.publico.pt. Acesso em: 5 dez. 2017 (adaptado). A concepção apresentada considera a existência de uma nova época geológica concebida a partir da capacidade de influência humana nos processos",
"(ENEM 2019) Em sentido geral e fundamental, Direito é a técnica da coexistência humana, isto é, a técnica voltada a tornar possível a coexistência dos homens. Como técnica, o Direito se concretiza em um conjunto de regras (que, nesse caso, são leis ou normas); e tais regras têm por objeto o comportamento intersubjetivo, isto é, o comportamento recíproco dos homens entre si. ABBAGNANO, N. Dicionário de Filosofia. São Paulo: Martins Fontes, 2007. O sentido geral e fundamental do Direito, conforme foi destacado, refere-se à",
"(ENEM 2019) As redes de alta tensão para transmissão de energia elétrica geram campo magnético variável o suficiente para induzir corrente elétrica no arame das cercas. Tanto os animais quanto os funcionários das propriedades rurais ou das concessionárias de energia devem ter muito cuidado ao se aproximarem de uma cerca quando esta estiver próxima a uma rede de alta tensão, pois, se tocarem no arame da cerca, poderão sofrer choque elétrico. Para minimizar este tipo de problema, deve-se:",
"(ENEM 2019) O concreto utilizado na construção civil é um material formado por cimento misturado a areia, a brita e a água. A areia é normalmente extraída de leitos de rios e a brita, oriunda da fragmentação de rochas. Impactos ambientais gerados no uso do concreto estão associados à extração de recursos minerais e ao descarte indiscriminado desse material. Na tentativa de reverter esse quadro, foi proposta a utilização de concreto reciclado moído em substituição ao particulado rochoso graúdo na fabricação de novo concreto, obtendo um material com as mesmas propriedades que o anterior. O benefício ambiental gerado nessa proposta é a redução do(a)",
"(ENEM 2019) Uma pessoa, que perdeu um objeto pessoal quando visitou uma cidade, pretende divulgar nos meios de comunicação informações a respeito da perda desse objeto e de seu contato para eventual devolução. No entanto, ela lembra que, de acordo com o Art. 1 234 do Código Civil, poderá ter que pagar pelas despesas do transporte desse objeto até sua cidade e poderá ter que recompensar a pessoa que lhe restituir o objeto em, pelo menos, 5% do valor do objeto. Ela sabe que o custo com transporte será de um quinto do valor atual do objeto e, como ela tem muito interesse em reavê-lo, pretende ofertar o maior percentual possível de recompensa, desde que o gasto total com as despesas não ultrapasse o valor atual do objeto. Nessas condições, o percentual sobre o valor do objeto, dado como recompensa, que ela deverá ofertar é igual a",
"(ENEM 2019) O preparador físico de um time de basquete dispõe de um plantel de 20 jogadores, com média de altura igual a 1,80 m. No último treino antes da estreia em um campeonato, um dos jogadores desfalcou o time em razão de uma séria contusão, forçando o técnico a contratar outro jogador para recompor o grupo. Se o novo jogador é 0,20 m mais baixo que o anterior, qual é a média de altura, em metro, do novo grupo?"
]

alternativas_a = ["desenvolvimento do pensamento autônomo. ",
"superprodução de bens de consumo.",
"eutrofização.",
"oscilação genética das raças.",
"suporte artístico.",
"divulgar um padrão oficial de redação e envio de currículos.",
"18",
"450",
"consagração de relacionamentos afetivos",
"eliminar a hierarquia militar",
"0",
"Ligações dissulfeto.",
"comparar elementos opostos",
"banalização da pirataria na rede.",
"22,00 cm, 12,00 cm e 5,00 cm.",
"22",
"espaço aberto para a aprendizagem.",
" “a singularidade”.",
"fundamentação científica de viés positivista.",
"promover a livre circulação de trabalhadores",
"ativando o sistema imunológico do hospedeiro.",
"volatilização das substâncias de interesse.",
"5",
"100",
"minimiza o alcance da comunicação digital.",
"conflito com os interesses de poder.",
"preservação cultural dos territórios ocupados.",
"expansão de áreas metropolitanas.",
"aproximação entre inovação e saberes antigos.",
"hidrolisar os lipídios.",
"512 000,00",
"36",
"restringir a investigação, deixando-a sob a responsabilidade do autor da carta.",
"primazia do samba sobre a música nordestina.",
"eruptivos",
"aplicação de códigos legais.", 
"fazer o aterramento dos arames da cerca.",
"extração da brita.",
"20%",
"1,60"]

alternativas_b = ["obtenção de qualificação profissional.",
"colapso industrial de países asiáticos.",
"proliferação de algas.",
"convergência adaptativa das raças", "nível tecnológico.",
"indicar um modelo de currículo para pleitear uma vaga de emprego.",
"26",
"500",
"administração da independência interior",
"abolir a escravidão africana.",
"1,18",
"Ligações covalentes.",
"relacionar informações gradativas.",
"adoção de medidas favoráveis aos editores.",
"27,50 cm, 15,00 cm e 6,25 cm.",
"50",
"grande número de ferramentas de pesquisa.",
" “tais vantagens”.",
"convenção social de orientação normativa",
"fomentar a competitividade no mercado externo.",
"interferindo na cascata bioquímica da inflamação.",
"polimerização dos óleos catalisada pela radiação solar.",
"10",
"400", 
"refuta ideias preconcebidas sobre o brasileiro.",
"silêncio em nome do equilíbrio familiar.",
"formação humanitária da sociedade europeia.",
"emancipação de novos municípios.",
"conciliação entre revelação e metafísica platônica.",
"agir como detergentes.",
"520 000,00",
"33",
"refutar possíveis causas da morte do cavalheiro, auxiliando na investigação.",
"inter-relação entre dois gêneros musicais brasileiros.",
"exógenos",
"regulação do convívio social.",
"acrescentar fusível de segurança na cerca.",
"extração de areia.", 
"25%",
"1,78" ]

alternativas_c = ["resgate de valores tradicionais.",
"interdependência do sistema econômico.",
"inibição da fotossíntese.",
"isolamento geográfico entre as raças.",
"base antropológica.",
"instruir o leitor sobre como ser eficiente no envio de currículo por e-mail.",
"30", 
"600",
"fugacidade do conhecimento empírico.",
"anular o domínio metropolitano.",
"116,96",
"Ligações hidrogênio.",
"intensificar um problema conceitual.",
"implementação de leis contra crimes eletrônicos.",
"34,37 cm, 18,75 cm e 7,81 cm.",
"100",
"ausência de mapas ou guias explicativos.",
"“os gabos”.",
"transgressão comportamental religiosa.",
"restringir investimentos de empresas multinacionais.",
"removendo as toxinas sintetizadas pelas bactérias.",
"solubilização das substâncias de interesse pelo orvalho.",
"15",
"1600", 
"relativiza responsabilidades sobre a noção de respeito",
"medo instaurado pelas ameaças de punição.",
"catalogação de dados úteis aos propósitos colonialistas.",
"consolidação de domínios jurídicos.",
"vinculação entre escolástica e práticas de pesquisa.",
"tornar os lipídios anfifílicos.",
"528 000,00",
"27",
"identificar o local da cena do crime, localizando-o no Jardim Lauriston.",
"valorização das origens oligárquicas da cultura nordestina. ",
"tectônicos",
"legitimação de decisões políticas.",
"realizar o aterramento da rede de alta tensão",
"consumo de água.",
"40%",
"1,79",]

alternativas_d = ["realização de desejos pessoais.",
"isolamento político dos países desenvolvidos.",
"fotodegradação da matéria orgânica.",
"seleção natural que ocorre entre as raças.",
"concepção estética.",
"responder a uma pergunta de um assinante da revista sobre o envio de currículo por e-mail.", 
"35",
"750",
"liberdade de expressão religiosa.",
"suprimir a propriedade fundiária.",
"816,96",
"Interações dipolo induzido – dipolo induzido",
"introduzir um argumento esclarecedor.",
"reavaliação do conceito de propriedade intelectual.",
"35,20 cm, 19,20 cm e 8,00 cm.", 
"200",
"infinito número de páginas virtuais.", 
"“Longe disso”.",
"racionalidade de caráter pragmático.",
"adotar medidas cambiais para subsidiar o setor agrícola.",
"combatendo as células hospedeiras das bactérias.",
"oxidação do óleo pelo oxigênio produzido na fotossíntese.",
"20",
"6250",
"exemplifica conceitos contidos na literatura e na sociologia.",
"choque imposto pela distância entre as gerações.",
"desenvolvimento de técnicas matemáticas de construção de cartas.",
"articulação de redes multiescalares.",
"separação entre teologia e fundamentalismo religioso.",
"promover a secreção de lipases.",
"552 000,00",
"24",
"introduzir o destinatário da carta, caracterizando sua personalidade.", 
"proposta de resgate de antigos gêneros musicais brasileiros.",
"magmáticos",
"mediação de conflitos econômicos.",
"instalar fusível de segurança na rede de alta tensão.",
"consumo de concreto.",
"60%",
"1,81"]


alternativas_e = ["aumento da renda familiar.",
"austeridade fiscal dos países em desenvolvimento.",
"aumento da quantidade de gases dissolvidos.", 
"manutenção do fluxo gênico entre as raças.",
"referencial temático.",
"orientar o leitor sobre como alcançar o maior número possível de selecionadores de currículos.", 
"60",
"1000",
"busca de prazeres efêmeros.",
"extinguir o absolutismo monárquico.",
"13 183,04",
"Interações dipolo permanente – dipolo permanente.",
"assinalar uma consequência hipotética.",
"ampliação do acesso a obras de autores reconhecidos.",  
"44,00 cm, 24,00 cm e 10,00 cm.",
"400",
"dificuldade de acesso aos sites de pesquisa.",
"“Em geral”.", 
"inclinação de natureza passional.", 
"reduzir a fiscalização alfandegária para incentivar o consumo.",
"danificando estruturas específicas da célula bacteriana",
"liberação das moléculas do óleo durante o processo de fotossíntese.",
"25",
"10000",
"expõe a ineficácia dos estudos para alterar tal comportamento.",
"apego aos protocolos de conduta segundo os gêneros.",
"consolidação do conhecimento topográfico como campo acadêmico.",
"redefinição de regiões administrativas.",
"contraposição entre clericalismo e liberdade de pensamento.", 
"estimular o trânsito intestinal dos lipídios.",
"584 000,00",
"21",
"apresentar o vigia, incluindo-o entre os suspeitos do assassinato.",
"criatividade em compor um samba-enredo em homenagem a uma pessoa.",
"metamórficos",
"representação da autoridade constituída.",
"utilizar fios encapados com isolante na rede de alta tensão.",
"fabricação de cimento.",
"80%",
"1,82" 
]